name: mga_members_app
description: "MGA application only for Member"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0 # For API calls
  provider: ^6.1.1 # For state management
  image_picker: ^1.1.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# Android Launcher Icon Config
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false # Bypasses iOS asset bundling
  image_path: "assets/icon/mga_members.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/icon/mga_members.png"

# Android Native Dark Boot Window Config
flutter_native_splash:
  color: "#212121"
  image: assets/icon/mga_members.png
  android_12:
    image: assets/icon/mga_members.png
    color: "#212121"
  fullscreen: true
